# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ncontin <ncontin@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/03 11:54:44 by ncontin           #+#    #+#              #
#    Updated: 2024/12/10 19:09:30 by ncontin          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = pipex.c \
		pipex_utils.c\

CC = gcc
CCFLAGS = -Wall -Wextra -Werror
RM = rm -f

libft = libft/libft.a

NAME = pipex

OBJ := $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	make -C libft
	$(CC)  $^ -Llibft -lft -o $(NAME)

%.o: %.c
	$(CC) $(CCFLAGS) -Iincludes -Ilibft -c $< -o $@

clean:
	$(RM) $(NAME)
	make clean -C libft

fclean: clean
	$(RM) $(NAME)
	make fclean -C libft

re: fclean all

.PHONY: all, clean, fclean, re
